NAME[0]="paddy"
NAME[1]="daddy"
NAME[2]="maddy"
NAME[3]="saddy"
NAME[4]="kaddy"
NAME[5]="laddy"
NAME[6]="waddy"
NAME[7]="qaddy"
echo "the NAME in array first time are: ${NAME[*]}"
echo "the NAME in array second time are: ${NAME[@]}"